public with sharing class B2B_Constants {
    
    public static final String EMAIL = 'email';
    public static final String PHONE = 'phone';
    public static final String IS_EMAIL_EXIST = 'isEmailExist';
    public static final String IS_PHONE_EXIST = 'isPhoneExist';
    public static final String IS_SUCCESS = 'isSuccess';
    public static final String ERROR_MSG = 'errorMsg';
    public static final String FIRST_NAME = 'firstName';
    public static final String LAST_NAME = 'lastName';
    public static final String ACCOUNT_ID = 'accountId';
    public static final String ACTIVE = 'Active';
    public static final String USER_ID = 'userId';
    public static final String CONTACT_ID = 'contactId';
    public static final String ACCOUNT_NAME = 'accountName';
    public static final String LOGIN_URL = 'loginUrl';
    public static final String USER_NAME = 'userName';
    public static final String PASSWORD = 'password';
    public static final String ERR_MSG = 'errorMsg';

    //Footer content
    public static final String COMPANY = 'company';
    public static final String DESCRIPTION = 'description';


    
}